Add rule checker and pricing for Stuart delivery
monsieurbiz/SyliusStuartDeliveryPlugin pull request #6
Opened 2022-04-13 13:49 UTC by lanfisis

- feat: add check and pricing methods to Stuart client
- feat: add Stuart rule checker configuration
- feat: add Stuart rule checker
- feat: add calculator and calculator configuration for Stuart delivery

2022-04-14 05:44 UTC, delyriand requested changes

2022-04-14 05:44 UTC, delyriand commented on src/Resources/translations/messages.fr.yaml
>    plugin_name: Livraison avec Stuart
you have reindent the `messsage.en` file but not this file

2022-04-14 05:44 UTC, delyriand commented on src/Stuart/AbstractServiceInteraction.php
> +abstract class AbstractServiceInteraction
```suggestion
abstract class AbstractServiceInteraction implements LoggerAwareInterface
```

2022-04-15 07:00 UTC, delyriand approved these changes

2022-04-19 07:16 UTC, maximehuran approved these changes

2022-04-20 10:40 UTC, merged